

CREATE TABLE DBUOC.EXPENSIVEPROJ (
	codProj TINYINT,
	price DECIMAL(9,2)
);

USE DBUOC;

CALL curdemo();

DROP PROCEDURE curdemo;

SELECT * FROM EXPENSIVEPROJ;

SELECT * FROM PROJECTS;

DELIMITER //
//
CREATE PROCEDURE curdemo()
BEGIN
  DECLARE done BOOLEAN DEFAULT FALSE;
  DECLARE priceProj DECIMAL(9,2);
  DECLARE codProj TINYINT;
  DECLARE cur1 CURSOR FOR SELECT cod_proj, price FROM DBUOC.PROJECTS;
  DECLARE CONTINUE HANDLER FOR sqlstate '02000' SET done = TRUE;
  DELETE FROM DBUOC.EXPENSIVEPROJ;
  OPEN cur1;
  FETCH cur1 INTO codProj, priceProj;
  WHILE NOT done  DO
    IF priceProj>1000000 THEN
         INSERT INTO DBUOC.EXPENSIVEPROJ VALUES (codProj,priceProj);
    END IF;
    FETCH cur1 INTO codProj, priceProj;
  END WHILE;
  CLOSE cur1;
END;
//
DELIMITER ;

CALL curdemo();

DROP PROCEDURE curdemo;

SELECT * FROM EXPENSIVEPROJ;

SELECT * FROM PROJECTS;
